# Generated by Django 4.0.5 on 2022-07-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_admin_signin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_signin',
        ),
    ]
