# Generated by Django 4.0.5 on 2022-07-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_delete_admin_signin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=255)),
                ('sample_location', models.CharField(max_length=255)),
                ('sample_dis', models.CharField(max_length=255)),
                ('sample_matrix', models.CharField(max_length=255)),
                ('sample_system', models.CharField(max_length=255)),
                ('sample_sampling', models.CharField(max_length=255)),
                ('gridRadios', models.CharField(max_length=255)),
                ('test1', models.CharField(max_length=255)),
                ('test2', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'analysis',
            },
        ),
    ]
