# Generated by Django 4.0.5 on 2022-07-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_sampletest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletest',
            name='gridRadios',
        ),
        migrations.RemoveField(
            model_name='sampletest',
            name='test1',
        ),
        migrations.RemoveField(
            model_name='sampletest',
            name='test2',
        ),
    ]
