# Generated by Django 4.0.5 on 2022-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_sampletest_gridradios_remove_sampletest_test1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampletest',
            name='gridRadios',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default=2, max_length=255),
            preserve_default=False,
        ),
    ]
