# Generated by Django 4.0.5 on 2022-08-01 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_sampletest_contename_sampletest_in_gram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampletest',
            name='contename',
        ),
        migrations.RemoveField(
            model_name='sampletest',
            name='in_gram',
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_in_moles', models.IntegerField()),
                ('name', models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.sampletest')),
            ],
            options={
                'db_table': 'contaminats',
            },
        ),
    ]
