# Generated by Django 4.0.5 on 2022-08-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_remove_sampletest_contename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
