# Generated by Django 4.0.5 on 2022-08-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_elements_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elements',
            old_name='name',
            new_name='conname',
        ),
    ]
