# Generated by Django 4.0.5 on 2022-08-01 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_rename_name_elements_conname'),
    ]

    operations = [
        migrations.AddField(
            model_name='elements',
            name='samid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.sampletest'),
        ),
    ]
