# Generated by Django 4.0.5 on 2022-08-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_elements_samid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elements',
        ),
    ]
