# Generated by Django 4.0.5 on 2022-07-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_delete_sampletest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samplename', models.CharField(max_length=255)),
                ('sampledate', models.DateField()),
                ('samplelocation', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Sample',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
