# Generated by Django 4.0.5 on 2022-07-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sample_delete_student'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sample',
            table='sample',
        ),
    ]
